// default package
// Generated 29/11/2017 10:26:09 AM by Hibernate Tools 5.2.3.Final

/**
 * SanPosts generated by hbm2java
 */
public class SanPosts implements java.io.Serializable {

	private Long pstId;
	private String pstContent;
	private int pstControl;

	public SanPosts() {
	}

	public SanPosts(String pstContent, int pstControl) {
		this.pstContent = pstContent;
		this.pstControl = pstControl;
	}

	public Long getPstId() {
		return this.pstId;
	}

	public void setPstId(Long pstId) {
		this.pstId = pstId;
	}

	public String getPstContent() {
		return this.pstContent;
	}

	public void setPstContent(String pstContent) {
		this.pstContent = pstContent;
	}

	public int getPstControl() {
		return this.pstControl;
	}

	public void setPstControl(int pstControl) {
		this.pstControl = pstControl;
	}

}
